### ISSUE TITLE
Panic occurs when action XML is not configured

### ISSUE THREAD

**Issue by ross-spencer** [ocfl-archive/gocfl#124]
In the default.toml if xml is set to false (or if default loaded from indexer library):

```toml
[Indexer.XML]
Enabled=false
```

```log
PNC error adding content to storageroot filesystem 'osFSRW(/tmp/gocfl-test)' error="cannot add folder 'osFSRW(/tmp/01JAG4HR8TBTX74AKTE8CPM
       │ HE8)' to 'rs:one:01JAG4HR8TBTX74AKTE8CPMHE8': cannot walk filesystem: cannot add file 'test-file-01JAG4HR8TBTX74AKTE8CPMHE8.file': cannot add file 'test-file-01JAG4
       │ HR8TBTX74AKTE8CPMHE8.file' to object: error on StreamObject() extension hook for object 'rs:one:01JAG4HR8TBTX74AKTE8CPMHE8': cannot call StreamObject() from extensi
       │ on 'NNNN-indexer' for object 'rs:one:01JAG4HR8TBTX74AKTE8CPMHE8': cannot index '[test-file-01JAG4HR8TBTX74AKTE8CPMHE8.file]': action 'xml' not configured" host=expo
       │ nential-decay stack=[{"func":"addObjectByPath","line":"349","source":"helper.go"},{"func":"doAdd","line":"291","source":"add.go"},{"func":"(*Command).execute","line
       │ ":"989","source":"command.go"},{"func":"(*Command).ExecuteC","line":"1117","source":"command.go"},{"func":"(*Command).Execute","line":"1041","source":"command.go"},
       │ {"func":"Execute","line":"232","source":"root.go"},{"func":"main","line":"16","source":"main.go"},{"func":"main","line":"272","source":"proc.go"},{"func":"goexit","
       │ line":"1700","source":"asm_amd64.s"}] timestamp="2024-10-18 17:39:43.816789018 +0200 CEST m=+0.031387504"
```

```sh
./gocfl add /tmp/gocfl-test /tmp/01JAG4HR8TBTX74AKTE8CPMHE8/ -u "ross" -a "ross@gocfl" -m "one file 01JAG4HR8TBTX74AKTE8CPMHE8" --object-id 'rs:one:01JAG4HR8TBTX74AKTE8CPMHE8' --log-level DEBUG
panic: error adding content to storageroot filesystem 'osFSRW(/tmp/gocfl-test)'
        panic: filesystem 'osFSRW(/tmp/gocfl-test)' not closed

goroutine 1 [running]:
github.com/ocfl-archive/gocfl/v2/gocfl/cmd.doAdd.func2.(*Logger).Panic.1({0xc0015a2060?, 0x0?})
        /home/ross-spencer/go/pkg/mod/github.com/rs/zerolog@v1.33.0/log.go:405 +0x27
github.com/rs/zerolog.(*Event).msg(0xc001594070, {0xc0015a2060, 0x2f})
        /home/ross-spencer/go/pkg/mod/github.com/rs/zerolog@v1.33.0/event.go:158 +0x2aa
github.com/rs/zerolog.(*Event).Msgf(0xc001594070, {0x1373ad1?, 0x17821a0?}, {0xc0018c2e88?, 0x439ac0?, 0xc0000061c0?})
        /home/ross-spencer/go/pkg/mod/github.com/rs/zerolog@v1.33.0/event.go:131 +0x46
github.com/ocfl-archive/gocfl/v2/gocfl/cmd.doAdd.func2()
        /home/ross-spencer/git/ocfl/gocfl/gocfl/cmd/add.go:214 +0xcb
panic({0x11591c0?, 0xc0019a8ca0?})
        /home/ross-spencer/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.1.linux-amd64/src/runtime/panic.go:785 +0x132
github.com/ocfl-archive/gocfl/v2/gocfl/cmd.doAdd.(*Logger).Panic.func20({0xc001aaa190?, 0x0?})
        /home/ross-spencer/go/pkg/mod/github.com/rs/zerolog@v1.33.0/log.go:405 +0x27
github.com/rs/zerolog.(*Event).msg(0xc001594070, {0xc001aaa190, 0x48})
        /home/ross-spencer/go/pkg/mod/github.com/rs/zerolog@v1.33.0/event.go:158 +0x2aa
github.com/rs/zerolog.(*Event).Msgf(0xc001594070, {0x139c491?, 0xc00158e1c8?}, {0xc0018c3c70?, 0x7ffcd2c03e23?, 0xa?})
        /home/ross-spencer/go/pkg/mod/github.com/rs/zerolog@v1.33.0/event.go:131 +0x46
github.com/ocfl-archive/gocfl/v2/gocfl/cmd.doAdd(0x2ad6b60, {0xc000170780, 0x2, 0x134e3c6?})
        /home/ross-spencer/git/ocfl/gocfl/gocfl/cmd/add.go:306 +0x1ed8
github.com/spf13/cobra.(*Command).execute(0x2ad6b60, {0xc0001706c0, 0xc, 0xc})
        /home/ross-spencer/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:989 +0xa91
github.com/spf13/cobra.(*Command).ExecuteC(0x2ad7120)
        /home/ross-spencer/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
        /home/ross-spencer/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041
github.com/ocfl-archive/gocfl/v2/gocfl/cmd.Execute()
        /home/ross-spencer/git/ocfl/gocfl/gocfl/cmd/root.go:232 +0x1a
main.main()
        /home/ross-spencer/git/ocfl/gocfl/gocfl/main.go:16 +0xf
```

Connected there's no section in the indexer defaults for XML [here](https://github.com/je4/indexer/blob/a02d015d6289f5687d43af935eb064ef104615a6/pkg/indexer/config.go#L159). 

It might need the following:

```golang
XML: ConfigXML{
  Enabled: true,
},
```

But I'm not sure the entirely intended behavior yet, probably avoiding the panic first, but making sure the log is meaningful if there is an impact.

**Comment by ross-spencer** [comment]
@je4 this took me a bit longer to find than anticipated. It may be expected behavior but I am not sure, and it would be good to get your opinion before closing this out.

I had expected that the `default.toml` would drive all of the configured indexing services. And throughout the early entry points, that config is used (it's what I have configured and compiled with), but when we get to `NewIndexerFS` it is overridden by a call to what I believe is an embedded `config.json` it is loaded here: https://github.com/ocfl-archive/gocfl/blob/714abede1dbf3edfd652811af5d7b5b47412560b/pkg/extension/NNNN-indexer.go#L47-L56

And the contents of what are loaded is are here: https://github.com/ocfl-archive/gocfl/blob/714abede1dbf3edfd652811af5d7b5b47412560b/data/fullextensions/object/NNNN-indexer/config.json#L1-L7

I feel like the behavior should be not to panic if it's not configured in the toml file, even if it is in config.json. Further, for the outside user, they might expect all config to be driven by a file they can supply, so again the toml. It seems like it can cause panics with other config settings like identify (but maybe all). But what do you think? Is there nuance I am missing?

An aside, but I wonder if in the entry-points, like `add.go` they can be moved from panics to what might be a slightly more idiomatic error and exit with non-zero code?

E.g. 

```diff
-               logger.Panic().Stack().Err(err).Msgf("error adding content to storageroot filesystem '%s'", destFS)
+               logger.Error().Stack().Err(err).Msgf("error adding content to storageroot filesystem '%s'", destFS)
+               os.Exit(1)
        }
```

It's a little more ergonomic to debug. I'm not sure how much it will mess too much with current workflows?
